language: ruby
script : script/cibuild
cache: bundler
sudo: false

before_install: gem update --system

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4

env:
  - ""
  - JEKYLL_VERSION=3.0

matrix:
  include:
    - # GitHub Pages
      rvm: 2.4.0
      env: GH_PAGES=true
